import os
import re

from pytrie.data import open_csv, open_fastq
from pytrie.trie import TrieNode, search

BASE_DIR = os.path.abspath(os.path.dirname(__file__))
DATA_PATH = os.path.join(os.path.abspath(os.path.dirname(__file__)), "data")
# Gets that only have nucleotides
SEQUENCE_RE = re.compile("^[actg]*$", re.IGNORECASE)


ref_path = os.path.join(DATA_PATH, "TN_20210930_alternate_barcodes_exhausted.csv")
ref_genes = open_csv(ref_path)["GeneName"].to_list()
ref_seqs = open_csv(ref_path)["Sequence"].to_list()
ref_gene_seq_hash = dict(list(zip(ref_seqs, ref_genes)))

ref_trie = TrieNode()
for seq in ref_seqs:
    ref_trie.insert(seq)

    # ref_trie.insert(seq)

example = [
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
    "ACGTAGGGATGATCGCTATTCGTACGCTGCAGGTCGACGGATCCCCGGGTTAAT",
]

for i in example:
    print(search(ref_trie, i, 2))
